### ISSUE TITLE
Place VMs to a specified datacenter

### ISSUE THREAD

**Issue by manoelcampos** [cloudsimplus/cloudsimplus-examples#10]
## Detailed information about how the feature should work

I want to place the current VM to a specified datacenter. For example, I have two Vms and two datacenters. I want to place Vm0 to datacenter0 and Vm1 to datacenter1. (Each datacenter has PEs that place two VMs at the same time)
As for the placement of Vm and Datacenter, I only know that VmAllocationPolicy is used to place Vm to the specified Host in the same datacenter. DatacenterSelectionByTimeZoneExample and SelectNextDatacenterExample of the cloudsim plus example module may also be related to this problem, but the situation is different.
I want to know if there are any relevant examples to place VMs in a specified datacenter，thanks！

## A brief explanation of why you think this feature is useful

Datacenters may have different characteristics, for example, their prices are different, and their performance is different. Therefore, when the Cloudlet comes, you need to allocate an appropriate Vm to the Cloudlet and place it in a more appropriate datacenter (for example, higher cost performance, or better matching of other parameters). This issue is also worthy of our attention.

**Comment by manoelcampos** [comment]
I think this is a great example to introduce in the repository and I've left this as an issue.

**Comment by manoelcampos** [comment]
Hey @wangdaoishere

I've created the [BrokerTargetDatacenterExample.java ](https://github.com/cloudsimplus/cloudsimplus-examples/blob/master/src/main/java/org/cloudsimplus/examples/brokers/BrokerTargetDatacenterExample.java) for CloudSim Plus 7.3.2 that shows how to do what you were looking for.

**Comment by wangdaoishere** [comment]
OK, thank you for enhancing this part. I will learn how to use it.
Thank you very much!

**Comment by wangdaoishere** [comment]
Thank you！
Maybe I understand how to allocate a VM to a specified datacenter. Each datacenter has its own broker. When I want to allocate a VM to a datacenter, I just need to submit it to the corresponding broker.
