### ISSUE TITLE
Parallel executions in CloudSimPlus

### ISSUE THREAD

**Issue by Lenkense** [cloudsimplus/cloudsimplus-examples#18]
I'm trying to execute 2 CloudSimPlus simulations on the same Java VM in order to train 2 different Reinforcement Learning agents. For some reason I keep getting only 1 simulation running when running them in different threads. 

Can CloudSimPlus execute in this way or should I run them in different VMs?

**Comment by manoelcampos** [comment]
Check [ParallelSimulationsExample.java](https://github.com/cloudsimplus/cloudsimplus-examples/blob/master/src/main/java/org/cloudsimplus/examples/ParallelSimulationsExample.java).
It runs multiple simulations inside the same JVM using Java 8 Parallel Streams.
