### ISSUE TITLE
Hi , in my opinion in cloudlet dynamic arrival2 the execution time for 3 cloudlets are not proper. Kindly look into it and correct me if I am wrong.

### ISSUE THREAD

**Issue by shalini151989** [cloudsimplus/cloudsimplus-examples#24]
# WHEN REPORTING AN ISSUE:

## Specifications like the version of the project, operating system or workload file used

------------------------------------------------------------------------------------------------------------------------------------

# WHEN REQUESTING A FEATURE:

**Comment by manoelcampos** [comment]
Please provide more information about the issue, filling in the questions presented when you create the issue (which you just left blank). Let me know that I reopen the issue.
