### ISSUE TITLE
NetworkVmsExampleSimpleApp does not work

### ISSUE THREAD

**Issue by Inverseit** [cloudsimplus/cloudsimplus-examples#26]
To report an issue or feature request, you have to provide the information below.

# WHEN REPORTING AN ISSUE:

## Actual behavior 
Simply running the `NetworkVmsExampleSimpleApp` (or `NetworkVmsExampleBagOfTasksApp` or `NetworkVmsExampleWorkflowApp`) without any changes after cloning this repository, the simulation ends earlier than expected with a default warning where a VM with running cloudlets inside.

Here are the logs:

`INFO  
================== Starting CloudSim Plus 8.5.0 ==================

INFO  0.00: #Datacenter 1 is starting...
INFO  org.cloudsimplus.network.switches.EdgeSwitch@49b1985 is starting...
INFO  Broker 3 is starting...
INFO  Entities started.
INFO  0.00: DatacenterBrokerSimple3: List of 1 datacenters(s) received.
INFO  0.00: DatacenterBrokerSimple3: Trying to create Vm 0 inside #Datacenter 1
INFO  0.00: DatacenterBrokerSimple3: Trying to create Vm 1 inside #Datacenter 1
INFO  0.00: NetworkHost: Vm 0 is booting up right away in Host 0/#DC 1, since no startup delay (boot time) was set.
INFO  0.00: VmAllocationPolicySimple: Vm 0 has been allocated to Host 0/#DC 1
INFO  0.00: NetworkHost: Vm 1 is booting up right away in Host 1/#DC 1, since no startup delay (boot time) was set.
INFO  0.00: VmAllocationPolicySimple: Vm 1 has been allocated to Host 1/#DC 1
INFO  0.10: DatacenterBrokerSimple3: Sending Cloudlet 0 to Vm 0 inside Host 0/#DC 1.
INFO  0.10: DatacenterBrokerSimple3: Sending Cloudlet 1 to Vm 1 inside Host 1/#DC 1.
INFO  0.10: DatacenterBrokerSimple3: All 2 waiting Cloudlets submitted to some VM.
INFO  4.10: Processing last events before simulation shutdown.
INFO  4.10: DatacenterBrokerSimple3 is shutting down...
INFO  4.10: NetworkVm: Requesting Vm 1 destruction on Host 1/#DC 1. Shutdown will finish immediately (since no Vm shutDownDelay was set).
INFO  4.10: NetworkVm: Requesting Vm 0 destruction on Host 0/#DC 1. Shutdown will finish immediately (since no Vm shutDownDelay was set).
WARN  4.10: #Datacenter 1: Vm 1 destroyed on Host 1/#DC 1. It had a total of 1 cloudlets (running + waiting). Some events may have been missed. You can try:
(a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute;
(b) increasing broker's Vm destruction delay for idle VMs if you set it to zero;
(c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).

WARN  4.10: #Datacenter 1: Vm 0 destroyed on Host 0/#DC 1. It had a total of 1 cloudlets (running + waiting). Some events may have been missed. You can try:
(a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute;
(b) increasing broker's Vm destruction delay for idle VMs if you set it to zero;
(c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).

INFO  Simulation: No more future events

INFO  CloudInformationService0: Notify all CloudSim Plus entities to shutdown.

INFO  EdgeSwitch2 is shutting down...
INFO  
================== Simulation finished at time 4.10 ==================

                                               SIMULATION RESULTS

|Cloudlet| Status|DC|Host|Host PEs |VM|   VM PEs|CloudletLen|FinishedLen|CloudletPEs|StartTime|FinishTime|ExecTime
|--------|-------|--|----|---------|--|---------|-----------|-----------|-----------|---------|----------|--------
|      ID|       |ID|  ID|CPU cores|ID|CPU cores|         MI|         MI|  CPU cores|  Seconds|   Seconds| Seconds

Host 0 data transferred: 0 bytes
Host 1 data transferred: 0 bytes
NetworkVmsExampleSimpleApp finished!

Process finished with exit code 0`

## Expected behavior
Cloudlets will be finished running before the VM gets destroyed. I am not sure, what the value of `schedulingInterval` to use or other numbers to change.

## What I have tried
I tried `setVmDestructionDelayFunction()` on broker, `setShutDownDelay()` and `setShutDownBeginTime()` on VM, but nothing. I also tried overwriting `processVmDestroy()`, however, it seems like **broker** is getting destroyed by itself.

## Specifications like the version of the project, operating system or workload file used:
OS: Mac OS Monterey, 12.6
Version: CloudSim Plus 8.5.0 
JDK: 21

**Comment by manoelcampos** [comment]
The issue was not related to the example, but a bug in the simulation core.
It was fixed in https://github.com/cloudsimplus/cloudsimplus/issues/475
