### ISSUE TITLE
Down Scaling of Ram in Vertical Scaling is buggy

### ISSUE THREAD

**Issue by greninja58** [cloudsimplus/cloudsimplus-examples#28]
## The Ram does not scale down while running the [VerticalVmRamScalingExample](https://github.com/cloudsimplus/cloudsimplus-examples/blob/master/src/main/java/org/cloudsimplus/examples/autoscaling/VerticalVmRamScalingExample.java)

**The Ram keeps scaling up as cloudlets arrive, with the in-built requestUpScaling method, but when there is only one cloudlet running it fails to reduce the amount of Ram allocated to the VM. Also even when the scaling factor or multiplier is large , it still keeps reporting that 0 Ram allocated/deallocated from Vm. Could you kindly suggest a way to make this work, or modify the core code?**

```
INFO  43.22: VerticalVmScalingSimple: 0 Ram deallocated from Vm 0: new capacity is 1000. Current resource usage is 100.0%     

Time   43.2: Vm 0 Ram Usage: 100.00% (1000 of 1000 MB) | Host Ram Allocation:  94.75% (18950 of 20000 MB).Running Cloudlets: 4
INFO  44.22: VerticalVmScalingSimple: 0 Ram deallocated from Vm 0: new capacity is 1000. Current resource usage is 100.0%     

Time   44.2: Vm 0 Ram Usage: 100.00% (1000 of 1000 MB) | Host Ram Allocation:  97.75% (19550 of 20000 MB).Running Cloudlets: 4
ERROR 45.22: VerticalVmScalingSimple: Vm 0 requested to reduce Ram capacity by 0 but an unexpected error occurred and the resource was not resized

Time   45.2: Vm 0 Ram Usage:  40.00% ( 400 of 1000 MB) | Host Ram Allocation:  97.75% (19550 of 20000 MB).Running Cloudlets: 4
ERROR 46.22: VerticalVmScalingSimple: Vm 0 requested to reduce Ram capacity by 0 but an unexpected error occurred and the resource was not resized
```

**Comment by manoelcampos** [comment]
Related issue: https://github.com/cloudsimplus/cloudsimplus/issues/392
