### ISSUE TITLE
Unexpected behavior in CloudletSchedulerTimeSharedExample1.java

### ISSUE THREAD

**Issue by StruffelProductions** [cloudsimplus/cloudsimplus-examples#6]
To report an issue or feature request, you have to provide the information below.

# WHEN REPORTING AN ISSUE:

## Actual behavior 

Running the example CloudletSchedulerTimeSharedExample1.java in org.cloudsimplus.examples.schedulers throws several warnings that cloudlets can't allocate enough RAM and bandwidth.

This causes the execution time of the second cloudlet to spike to astronimical levels, which I don't believe to be the desired behavior in this demo.
(Note about the included log: I tried resolving this by increasing the resources of hosts and vms which changes the absolute values but didn't resolve the issue.)
```
[34mINFO  
================== Starting CloudSim Plus 7.3.0 ==================

[0;39m[34mINFO  0,00: DatacenterSimple1 is starting...
[0;39m[34mINFO  DatacenterBrokerSimple2 is starting...
[0;39m[34mINFO  Entities started.
[0;39m[34mINFO  0,00: DatacenterBrokerSimple2: List of 1 datacenters(s) received.
[0;39m[34mINFO  0,00: DatacenterBrokerSimple2: Trying to create Vm 0 in DatacenterSimple1
[0;39m[34mINFO  0,00: VmAllocationPolicySimple: Vm 0 has been allocated to Host 0/DC 1
[0;39m[34mINFO  0,10: DatacenterBrokerSimple2: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
[0;39m[34mINFO  0,10: DatacenterBrokerSimple2: Sending Cloudlet 1 to Vm 0 in Host 0/DC 1.
[0;39m[34mINFO  0,10: DatacenterBrokerSimple2: All 2 waiting Cloudlets submitted to some VM.
[0;39m[31mWARN  10,10: CloudletSchedulerTimeShared: Cloudlet 1 requested 2048 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  10,10: CloudletSchedulerTimeShared: Cloudlet 1 requested 2000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[31mWARN  20,00: CloudletSchedulerTimeShared: Cloudlet 1 requested 2048 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  20,00: CloudletSchedulerTimeShared: Cloudlet 1 requested 2000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[31mWARN  20,11: CloudletSchedulerTimeShared: Cloudlet 1 requested 2048 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  20,11: CloudletSchedulerTimeShared: Cloudlet 1 requested 2000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[34mINFO  20,11: DatacenterBrokerSimple2: Cloudlet 0 finished in Vm 0 and returned to broker.
[0;39m[34mINFO  9223372066,74: DatacenterBrokerSimple2: Cloudlet 1 finished in Vm 0 and returned to broker.
[0;39m[34mINFO  9223372066,96: Processing last events before simulation shutdown.
[0;39m[34mINFO  9223372066,96: DatacenterBrokerSimple2 is shutting down...
[0;39m[34mINFO  9223372066,96: DatacenterBrokerSimple2: Requesting Vm 0 destruction.
[0;39m[34mINFO  9223372066,96: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1. 
[0;39m[34mINFO  Simulation: No more future events

[0;39m[34mINFO  CloudInformationService0: Notify all CloudSim Plus entities to shutdown.

[0;39m[34mINFO  
================== Simulation finished at time 9223372066,96 ==================

[0;39m

                                               SIMULATION RESULTS

|Cloudlet|Status |DC|Host|Host PEs |VM|VM PEs   |CloudletLen|FinishedLen|CloudletPEs|StartTime|FinishTime|ExecTime
|--------|-------|--|----|---------|--|---------|-----------|-----------|-----------|---------|----------|--------
|      ID|       |ID|  ID|CPU cores|ID|CPU cores|         MI|         MI|  CPU cores|  Seconds|   Seconds| Seconds
|       0|SUCCESS| 1|   0|        4| 0|        2|      10000|      10000|          2|        0|        20|      20
|       1|SUCCESS| 1|   0|        4| 0|        2|      10000|      10000|          2|        0|9223372067|9223372067
```

## Expected behavior

Based on the comment I would expect both VMs to finish at the same time.

## If the issue is related to a specific method, provide a test case that fails in order to show the problem
N/A

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem

In think this has to do with the utilization model that is created in line 168. It requests 100% of all resources not just for the CPU but also for all the other resources. I replaced it with a `new UtilizationModelDynamic(0.5);` and was able to get both VMs to finish at the same time (though twice as slow obviously). But this kind of misses the point of the demo as far as I see it.

## Specifications like the version of the project, operating system or workload file used
Cloudsimplus-examples, commit ff8c7f6f12f64a4d02419ec6d4e60f23149286b3 (latest as of right now)
Run in Eclipse as a maven project with openjdk 17.0.4

**Comment by manoelcampos** [comment]
Hey @StruffelProductions 
Most of these examples are inherited from CloudSim, where only the UtilizationModelFull was available.
They are using UtilizationModelFull for RAM and BW when there are multiple Cloudlets running in parallel inside a given VM. There is no way for 2 parallel cloudlets to use 100% of RAM at the same time.

This way, such examples need to use a different UtilizationModel, such as UtilizationModelDynamic, for RAM and BW. Check related issue https://github.com/cloudsimplus/cloudsimplus/issues/126

I've just updated this example, but certanly there is more.

**Comment by manoelcampos** [comment]
Thanks for reporting.

**Comment by manoelcampos** [comment]
I've fixed in all available examples.

**Comment by manoelcampos** [comment]
The bottom line is: is you are using a CloudletSchedulerTimeShared and have more than one Cloudlet running in parallel (on distinct VM PEs), there is no way two Cloudlets can use 100% of RAM or BW at the same time. The first Cloudlet to be processed inside that VM at time t receives 100% of such resources, while the other Cloudlet never gets the chance to use them. This explains why the second Cloudlet execution time gets an unresonable value.
